---
abstract: 'DCE compatible Universally Unique Identifier library for Perl'
author:
  - 'Rick Myers <jrm@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test: '0'
configure_requires:
  Devel::CheckLib: '1.02'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.142690'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: UUID
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.005'
version: '0.19'
